name: CI

on:
  push:
    branches: 
      - "**"
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init

      - run: ./scripts/gen.sh

      - run: ./scripts/build.sh 0.1.0
